/*
# Copyright (c) 2021-2025 University of Missouri                   
# Author: Xing Song, xsm7f@umsystem.edu                            
# File: als-case-omop.sql
# Description: multifactorial computable phenotype for identifying ALS patients (CDC alg)
# Dependency: 
# - REF_ALS_CDE: generated by staging the ./ref/als_cde.csv reference table  
# - OMOP CDM Tables
*/

select * from REF_ALS_CDE limit 5;

/* check other dependency table status */
set path_to_omop = 'OMOP_CDM.CDM';
set omop_vocabulary = $path_to_omop || '.VOCABULARY';
set omop_concept = $path_to_omop || '.CONCEPT';
set omop_drugexposure = $path_to_omop || '.DRUG_EXPOSURE';
set omop_person = $path_to_omop || '.PERSON';
set omop_person = $path_to_omop || '.PERSON';

select * from identifier($omop_vocabulary);
select * from identifier($omop_concept) limit 5;
select * from identifier($omop_drugexposure) limit 5;
select * from identifier($omop_person) limit 5;

select * from OMOP_CDM.CDM.CONDITION_OCCURRENCE limit 5;
select * from OMOP_CDM.CDM.PROCEDURE_OCCURRENCE limit 5;
select * from OMOP_CDM.CDM. limit 5;

select * from OMOP_CDM.CDM.VISIT_OCCURRENCE limit 5;
select * from OMOP_CDM.CDM.VISIT_OCCURRENCE where care_site_id is not null limit 5;
select * from OMOP_CDM.CDM.CARE_SITE limit 5;
select * from OMOP_CDM.CDM.CARE_SITE where care_site_name is not null limit 5;
select distinct care_site_name from OMOP_CDM.CDM.CARE_SITE
where lower(care_site_name) like '%neuro%';
select * from OMOP_CDM.CDM.PROVIDER limit 5;
select * from OMOP_CDM.CDM.PROVIDER where specialty_concept_id is not null limit 5;


/*
apply CDC alg. and identify ALS cases
- ICD9: 335.20; ICD10: G12.21
- visit to neurologist
- use of riluzole or endaravone or tofersen
- covered by CMS when age under 65 yo
*/
create or replace table ALS_EVENT_LONG (
    PATID varchar(50) NOT NULL,
    EVENT_TYPE varchar(20),
    EVENT_DATE date,     
    AGE_AT_EVENT integer,
    EVENT_SRC varchar(10)
);
insert into ALS_EVENT_LONG
with dx_cset as (
      select distinct ref.name, cd.concept_id
      from identifier($omop_concept) cd
      join REF_ALS_CDE ref 
      on cd.concept_code like ref.code || '%' and 
         upper(ref.codesystem) = upper(cd.vocabulary_id)
      where ref.codesystem in (
                  'icd9cm',
                  'icd10cm'
            ) and 
            ref.op = 'descendent-of'
      union
      select distinct ref.name, cd.concept_id
      from identifier($omop_concept) cd
      join REF_ALS_CDE ref 
      on cd.concept_code like ref.code || '%' and 
         upper(ref.codesystem) = upper(cd.vocabulary_id)
      where ref.codesystem in (
                  'icd9cm',
                  'icd10cm'
            ) and 
            ref.op = 'exists'
)
select a.person 

from 
;


create or replace table ALS_CASE_TABLE1 as
with cte_ord as (
    select a.patid, 
           a.event_type,
           a.event_date,
           a.age_at_event,
           a.event_src,
           count(distinct a.event_type) over (partition by a.patid) as distinct_event_cnt,
           count(distinct a.event_date) over (partition by a.patid) as distinct_date_cnt,
           listagg(distinct a.event_type, '|') within group (order by a.event_type) over (partition by a.patid) as event_str,
           max(case when b.chart = 'Y' then 1 else 0 end) over (partition by a.patid) as complt_ind,
           max(case when b.enr_start_date is null then 1 else 0 end) over (partition by a.patid) as ehr_ind,
           row_number() over (partition by a.patid order by a.event_date) as rn
    from ALS_EVENT_LONG a
    left join GROUSE_DB.CMS_PCORNET_CDM.LDS_ENROLLMENT b 
    on a.patid = b.patid
), cte_dx1 as(
    select patid,
           min(event_date) as als1dx_date
    from ALS_EVENT_LONG
    where event_type = 'DX'
    group by patid
)
select a.patid 
      ,b.birth_date
      ,b.sex
      ,b.race 
      ,b.hispanic
      ,c.als1dx_date
      ,a.event_type as index_event
      ,case when a.event_type = 'NEUROLOGIST' then c.als1dx_date else a.event_date end as index_date
      ,case when a.event_type = 'NEUROLOGIST' then round(datediff(day,b.birth_date,c.als1dx_date)/365.25) else a.age_at_event end as age_at_index
      ,a.event_src as index_src
      ,a.distinct_event_cnt
      ,a.distinct_date_cnt
      ,a.event_str
      ,case when a.complt_ind = 1 then 'complete'
            when a.complt_ind = 0 and a.ehr_ind = 1 then 'enr_only'
            else 'cms_only'
       end as complt_flag
      ,case when a.distinct_event_cnt > 2 then 'confirmed'
            else 'likely'
       end as case_assert 
from cte_ord a 
join PAT_TABLE1 b on a.patid = b.patid
join cte_dx1 c on a.patid = c.patid
where a.rn = 1 and b.birth_date is not null
      and a.distinct_date_cnt > 1 
      and (a.event_str like '%DX%' and a.event_str <> 'DX') -- at least likely, only 1 DX is considered "undetermined"
;



/*
ALS_CASE_TABLE1 will be loaded into R for downstream analyses: 
- ./src/R/extract.R: extract final tables into R and save as rdata files
- ./src/R/explore.R: generate descriptive reports
- ./src/R/pec.R: a positive exposure control test on Riluzole effectiveness
*/



