/*
# Copyright (c) 2021-2025 University of Missouri                   
# Author: Xing Song, xsm7f@umsystem.edu                            
# File: als-case-omop.sql
# Description: multifactorial computable phenotype for identifying ALS patients (CDC alg)
# Dependency: 
# - REF_ALS_CDE: generated by staging the ./ref/als_cde.csv reference table  
# - Current OMOP CDM Tables
*/

select * from REF_ALS_CDE limit 5;

/* check other dependency table status */
set path_to_omop = 'OMOP_CDM.CDM';
set omop_vocabulary = $path_to_omop || '.VOCABULARY';
set omop_concept = $path_to_omop || '.CONCEPT';
set omop_drug_exposure = $path_to_omop || '.DRUG_EXPOSURE';
set omop_person = $path_to_omop || '.PERSON';
set omop_condition_occurrence= $path_to_omop || '.CONDITION_OCCURRENCE';
set omop_visit_occurrence= $path_to_omop || '.VISIT_OCCURRENCE';
set omop_care_site= $path_to_omop || '.CARE_SITE';
set omop_provider= $path_to_omop || '.PROVIDER';
set omop_procedure_occurrence= $path_to_omop || '.PROCEDURE_OCCURRENCE';
set omop_payer_plan_period= $path_to_omop || '.PAYER_PLAN_PERIOD';

select * from identifier($omop_vocabulary);
select * from identifier($omop_concept) limit 5;
select * from identifier($omop_person) limit 5;
select * from identifier($omop_condition_occurrence) limit 5;
select * from identifier($omop_visit_occurrence) limit 5;
select * from identifier($omop_care_site) limit 5;
select * from identifier($omop_provider) limit 5;
select * from identifier($omop_drug_exposure) limit 5;
select * from identifier($omop_procedure_occurrence) limit 5;
select * from identifier($omop_payer_plan_period) limit 5;


/*
apply CDC alg. and identify ALS cases
- ICD9: 335.20; ICD10: G12.21
- visit to neurologist
- use of riluzole or endaravone or tofersen
- covered by CMS when age under 65 yo
*/
create or replace table ALS_EVENT_LONG (
    PERSON_ID varchar(50) NOT NULL,
    EVENT_TYPE varchar(20),
    EVENT_DATE date,     
    AGE_AT_EVENT integer,
    EVENT_DETAIL varchar(100),
    EVENT_SRC varchar(10)
);
-- diagnoses
insert into ALS_EVENT_LONG
with dx_cset as (
      select distinct ref.name, cd.concept_id
            -- , cd.concept_name, cd.concept_code
      from identifier($omop_concept) cd
      join REF_ALS_CDE ref 
      on cd.concept_code like ref.code || '%' and 
         upper(ref.codesystem) = upper(cd.vocabulary_id)
      where ref.codesystem in (
                  'icd9cm',
                  'icd10cm'
            ) and 
            ref.op = 'descendent-of' and ref.name = 'DiagnosALS'
      union
      select distinct ref.name, cd.concept_id
            -- , cd.concept_name, cd.concept_code
      from identifier($omop_concept) cd
      join REF_ALS_CDE ref 
      on cd.concept_code like ref.code || '%' and 
         upper(ref.codesystem) = upper(cd.vocabulary_id)
      where ref.codesystem in (
                  'icd9cm',
                  'icd10cm'
            ) and 
            ref.op = 'exists' and ref.name = 'DiagnosALS'
)
select a.person_id, 
       'DX' as EVENT_TYPE,
       a.condition_start_date as EVENT_DATE,
       year(a.condition_start_date) - p.year_of_birth as AGE_AT_EVENT,
       b.name as EVENT_DETAIL,
       'CONDITION_OCCURRENCE' as EVENT_SRC     
from identifier($omop_condition_occurrence) a 
join dx_cset b on a.condition_concept_id = b.concept_id
join identifier($omop_person) p on a.person_id = p.person_id
;

-- drug
insert into ALS_EVENT_LONG
with dx_cset as (
      select distinct ref.name, cd.concept_id
            -- , cd.concept_name, cd.concept_code
      from identifier($omop_concept) cd
      join REF_ALS_CDE ref 
      on cd.concept_code like ref.code || '%' and 
         upper(ref.codesystem) = upper(cd.vocabulary_id)
      where ref.codesystem in (
                  'rxnorm',
                  'ndc'
            ) and 
            ref.op = 'exists' and ref.name in ('riluzole','edaravone','toferson')
)
select a.person_id, 
       'DX' as EVENT_TYPE,
       a.condition_start_date as EVENT_DATE,
       year(a.condition_start_date) - p.year_of_birth as AGE_AT_EVENT,
       b.name as EVENT_DETAIL,
       'CONDITION_OCCURRENCE' as EVENT_SRC     
from identifier($omop_condition_occurrence) a 
join dx_cset b on a.condition_concept_id = b.concept_id
join identifier($omop_person) p on a.person_id = p.person_id
;


create or replace table ALS_CASE_TABLE1 as
with cte_ord as (
    select a.patid, 
           a.event_type,
           a.event_date,
           a.age_at_event,
           a.event_src,
           count(distinct a.event_type) over (partition by a.patid) as distinct_event_cnt,
           count(distinct a.event_date) over (partition by a.patid) as distinct_date_cnt,
           listagg(distinct a.event_type, '|') within group (order by a.event_type) over (partition by a.patid) as event_str,
           row_number() over (partition by a.patid order by a.event_date) as rn
    from ALS_EVENT_LONG a
), cte_dx1 as(
    select patid,
           min(event_date) as als1dx_date
    from ALS_EVENT_LONG
    where event_type = 'DX'
    group by patid
)
select a.patid 
      ,b.birth_date
      ,b.sex
      ,b.race 
      ,b.hispanic
      ,c.als1dx_date
      ,a.event_type as index_event
      ,case when a.event_type = 'NEUROLOGIST' then c.als1dx_date else a.event_date end as index_date
      ,case when a.event_type = 'NEUROLOGIST' then round(datediff(day,b.birth_date,c.als1dx_date)/365.25) else a.age_at_event end as age_at_index
      ,a.event_src as index_src
      ,a.distinct_event_cnt
      ,a.distinct_date_cnt
      ,a.event_str
from cte_ord a 
join PAT_TABLE1 b on a.patid = b.patid
join cte_dx1 c on a.patid = c.patid
where a.rn = 1 and b.birth_date is not null
      and a.distinct_date_cnt > 1 
      and (a.event_str like '%DX%' and a.event_str <> 'DX') -- at least likely, only 1 DX is considered "undetermined"
;

-- N(total) of eligible ALS patients
select count(distinct patid) from ALS_CASE_TABLE1;

-- N of different computable phenotypes
select event_src, count(distinct patid) from ALS_CASE_TABLE1
group by event_src
;

